export const SELECT_FILTER_OPTION = "SELECT_FILTER_OPTION";
export const SELECT_SORT_OPTION = "SELECT_SORT_OTION";
export const SEARCH_INPUT = "SEARCH_INPUT";
export const MODAL_TOGGLE = "MODAL_TOGGLE";
